Continuous Study/Django/music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<album_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<album_id>\d+)/favorite/$', views.favorite, name='favorite')
]

Continuous Study/Django/pydjis/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # Examples:
    # url(r'^$', 'pydjis.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls'))
]

Continuous Study/Django/music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=130)
    title = models.CharField(max_length=250)
    genre = models.CharField(max_length=70)
    logo = models.CharField(max_length=1000)

    def __str__(self):
        return " BY ".join((self.title, self.artist))

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return " FROM ".join((self.title, str(self.album)))

Continuous Study/Django/music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song


def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums':all_albums})

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album':album})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        sel_song = album.song_set.get(pk=request.POST['song'])
    

Continuous Study/Django/music/templates/music/detail.html
<h1>{{ album.title }}</h1>
<h2>{{ album.artist }}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
        <label for="song{{ forloop.counter }}">
            {{ song.title }}
            {% if song.is_favorite %}
                <b>fav</b>
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

Continuous Study/Django/music/templates/music/index.html
{% if all_albums %}
    <h3>Albums available:</h3>
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>No albums</h3>
{% endif %}